# Generated by packaging/homebrew.sh in jacobsieradzki/pyscythe. Do not edit.
class Pyscythe < Formula
  desc "Dead code, import cycles, duplication, and complexity for Python codebases"
  homepage "https://github.com/jacobsieradzki/pyscythe"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/jacobsieradzki/pyscythe/releases/download/v0.3.0/pyscythe-0.3.0-aarch64-apple-darwin.tar.gz"
      sha256 "94ae849a92db04235ac579feb7ba8f8d8465b49e47230e59c65194a157b4a434"
    end
    on_intel do
      url "https://github.com/jacobsieradzki/pyscythe/releases/download/v0.3.0/pyscythe-0.3.0-x86_64-apple-darwin.tar.gz"
      sha256 "3034591f62713f537b121eb7b7266f2404b3e470194caa3bd57a383e17bb0034"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/jacobsieradzki/pyscythe/releases/download/v0.3.0/pyscythe-0.3.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "675dda2b4055f428403aa5a0f2916a57311bba266c132bb90de1da89127688a1"
    end
    on_intel do
      url "https://github.com/jacobsieradzki/pyscythe/releases/download/v0.3.0/pyscythe-0.3.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "9d11bfc41b405a357629852159850374a0028c96264a432ce9c87b58f5f9273a"
    end
  end

  def install
    bin.install "pyscythe"
  end

  test do
    assert_match "pyscythe #{version}", shell_output("#{bin}/pyscythe --version")

    (testpath/"pkg/__init__.py").write ""
    (testpath/"pkg/dead.py").write "def never_called():\n    return 1\n"
    # A finding is exit code 1, which is the point of the tool.
    assert_match "pkg.dead", shell_output("#{bin}/pyscythe dead-code #{testpath}", 1)
  end
end
